# Generated by Django 4.1.4 on 2023-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bitdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bitmartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('mob', models.IntegerField(blank=True, null=True)),
                ('uname', models.CharField(blank=True, max_length=30, null=True)),
                ('pswd', models.CharField(blank=True, max_length=30, null=True)),
                ('cpswd', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
                ('pname', models.CharField(blank=True, max_length=30, null=True)),
                ('qua', models.IntegerField(blank=True, null=True)),
                ('pri', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
