# Generated by Django 4.1.4 on 2023-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admins_category_products_delete_bitdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Quantity',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
