# Generated by Django 4.1.4 on 2023-01-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Quantity',
            new_name='Models',
        ),
    ]
