# Generated by Django 4.1.4 on 2023-01-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_quantity_products_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='Specification',
        ),
    ]
